const group1 = [
  { id: 1, translation: "myśleć ", text: "think", active: false },
  { id: 2, translation: "potrzebować", text: "need", active: false },
  { id: 3, translation: "rozmawiać", text: "talk", active: false },
  { id: 4, translation: "zostać", text: "stay", active: false },
  { id: 5, translation: "jechać autem", text: "drive", active: false },
  { id: 6, translation: "zgadzać się ", text: "agree", active: false },
  {
    id: 7,
    translation: "ściągać (ubranie) ",
    text: "pull down",
    active: false,
  },
  { id: 8, translation: "zgadywać", text: "guess", active: false },
  { id: 9, translation: "zgadywać", text: "mean", active: false },
  {
    id: 10,
    translation: "nosić (ciuchy) ",
    text: "wear",
    active: false,
  },
  {
    id: 11,
    translation: "naprawić, zamocować ",
    text: "fix",
    active: false,
  },
  {
    id: 12,
    translation: "pójść za kimś, śledzić",
    text: "follow",
    active: false,
  },
  {
    id: 13,
    translation: "wpaść do kogoś ",
    text: "drop in ",
    active: false,
  },
  { id: 14, translation: "doręczać ", text: "deliver", active: false },
  { id: 15, translation: "stosować", text: "apply", active: false },
  {
    id: 16,
    translation: "facaprzepraszać za cośde",
    text: "apologize",
    active: false,
  },
  { id: 17, translation: "chrapać", text: "snore", active: false },
  { id: 18, translation: "rozejrzeć się", text: "look around ", active: false },
  {
    id: 19,
    translation: "rozwiązać problem (potocznie) ",
    text: "sort out ",
    active: false,
  },
  { id: 20, translation: "popierać kogoś", text: "back sb up ", active: false },
  { id: 21, translation: "montować", text: "assemble", active: false },
  { id: 22, translation: "aportować", text: "fetch", active: false },
  { id: 23, translation: "zniechęcać", text: "discourage", active: false },
  {
    id: 24,
    translation: "zgłaszać, meldować",
    text: "report",
    active: false,
  },
  { id: 25, translation: "pochwalić", text: "praise", active: false },
  {
    id: 26,
    translation: "odrzucać (ofertę)",
    text: "turn down",
    active: false,
  },
  { id: 27, translation: "pielęgnować", text: "nurture ", active: false },
  { id: 28, translation: "wyróżniać się", text: "stand out", active: false },
  { id: 29, translation: "wabić", text: "lure", active: false },
  { id: 30, translation: "odbywać próby", text: "rehearse", active: false },
];

const group2 = [
  {
    id: 1,
    translation: "ozwodzić się nad czymś",
    text: "dwell",
    active: false,
  },
  { id: 2, translation: "warczeć", text: "growl", active: false },
  { id: 3, translation: "wzdymać", text: "bloat", active: false },
  { id: 4, translation: "wzbogacać ", text: "enrich", active: false },
  { id: 5, translation: "oburzać się", text: "resent", active: false },
  { id: 6, translation: "ulec", text: "succumb", active: false },
  { id: 7, translation: "ludzie", text: "people", active: false },
  { id: 8, translation: "biżuteria", text: "jewellery", active: false },
  { id: 9, translation: "sok", text: "juice", active: false },
  { id: 10, translation: "ubrania", text: "clothes", active: false },
  { id: 11, translation: "fotel", text: "armchair", active: false },
  { id: 12, translation: "miska", text: "bowl", active: false },
  { id: 13, translation: "lek", text: "medicine", active: false },
  { id: 14, translation: "szyja", text: "neck", active: false },
  { id: 15, translation: "chodnik", text: "pavement", active: false },
  { id: 16, translation: "koc", text: "text", active: false },
  { id: 17, translation: "ręcznik", text: "blanket", active: false },
  { id: 18, translation: "przyczyna", text: "towel", active: false },
  { id: 19, translation: "ilość", text: "cause", active: false },
  { id: 20, translation: "gołąb", text: "quantity", active: false },
  { id: 21, translation: "mąka", text: "pigeon", active: false },
  { id: 22, translation: "gniazdko elektrycze", text: "flour", active: false },
  { id: 23, translation: "grubość", text: "socket", active: false },
  { id: 24, translation: "kamienica", text: "harbour", active: false },
  { id: 25, translation: "podkoszulek", text: "thickness", active: false },
];

const group3 = [
  { id: 1, translation: "cecha", text: "tenement", active: false },
  { id: 2, translation: "trawnik", text: "undershirt", active: false },
  { id: 3, translation: "urządzenie domowe", text: "feature", active: false },
  { id: 4, translation: "deska", text: "lawn", active: false },
  { id: 5, translation: "gęstość", text: "appliance", active: false },
  { id: 6, translation: "bocian", text: "plank", active: false },
  { id: 7, translation: "kołyska", text: "density", active: false },
  { id: 8, translation: "obojczyk", text: "stork", active: false },
  { id: 9, translation: "przysięga", text: "cradle", active: false },
  { id: 10, translation: "paproć", text: "collar bone ", active: false },
  { id: 11, translation: "erudyta", text: "oath", active: false },
  { id: 12, translation: "skowronek", text: "fern", active: false },
  { id: 13, translation: "maczuga", text: "prig/scholar", active: false },
  { id: 14, translation: "rozpuszczalnik", text: "lark", active: false },
  { id: 15, translation: "podwozie", text: "bludgeon", active: false },
  { id: 16, translation: "łom", text: "solvent", active: false },
  { id: 17, translation: "facade", text: "chassis", active: false },
  { id: 18, translation: "dobry", text: "good", active: false },
  { id: 19, translation: "biedny", text: "poor", active: false },
  { id: 20, translation: "wspaniały", text: "great", active: false },
  { id: 21, translation: "sprytny, bystry ", text: "soft", active: false },
  { id: 22, translation: "cichy", text: "clever", active: false },
  { id: 23, translation: "podobny", text: "silent", active: false },
  { id: 24, translation: "powoli", text: "similar", active: false },
  { id: 25, translation: "wąski", text: "slowly", active: false },
];

const group4 = [
  { id: 1, translation: "gorzki", text: "bitter", active: false },
  { id: 2, translation: "rzadki", text: "rare", active: false },
  { id: 3, translation: "paskudny, wstrętny", text: "nasty", active: false },
  { id: 4, translation: "pewien (określony) ", text: "certain", active: false },
  { id: 5, translation: " nowoczesny", text: "modern", active: false },
  { id: 6, translation: "prosto", text: "straight", active: false },
  { id: 7, translation: "zwykły", text: "ordinary", active: false },
  { id: 8, translation: "roztopiony", text: "melted", active: false },
  { id: 9, translation: "dogodny", text: "convenient", active: false },
  { id: 10, translation: "zwinny", text: "agile", active: false },
  {
    id: 11,
    translation: "znaczący, ważny",
    text: "significant",
    active: false,
  },
  {
    id: 12,
    translation: "niewystarczający",
    text: "insufficient",
    active: false,
  },
  { id: 13, translation: "podmiejski", text: "suburban", active: false },
  { id: 14, translation: "suburban", text: "suburban", active: false },
  { id: 15, translation: "czujny", text: "alert", active: false },
  { id: 16, translation: "krzywy", text: "crooked", active: false },
  { id: 17, translation: "zczery do bólu", text: "outspoken", active: false },
  { id: 18, translation: "sumienny", text: "conscientous", active: false },
  { id: 19, translation: "chropowaty", text: "gnarly", active: false },
  { id: 20, translation: "niemodnie", text: "dowdy", active: false },
];

module.exports = { group1, group2, group3, group4 };
