const group1 = [
  { id: 1, text: "facade", translation: "translation" },
  { id: 2, text: "facade", translation: "translation" },
  { id: 3, text: "facade", translation: "translation" },
  { id: 4, text: "facade", translation: "translation" },
  { id: 5, text: "facade", translation: "translation" },
  { id: 6, text: "facade", translation: "translation" },
  { id: 7, text: "facade", translation: "translation" },
  { id: 8, text: "facade", translation: "translation" },
  { id: 9, text: "facade", translation: "translation" },
  { id: 10, text: "facade", translation: "translation" },
  { id: 11, text: "facade", translation: "translation" },
  { id: 12, text: "facade", translation: "translation" },
  { id: 13, text: "facade", translation: "translation" },
  { id: 14, text: "facade", translation: "translation" },
  { id: 15, text: "facade", translation: "translation" },
  { id: 16, text: "facade", translation: "translation" },
  { id: 17, text: "facade", translation: "translation" },
  { id: 18, text: "facade", translation: "translation" },
  { id: 19, text: "facade", translation: "translation" },
  { id: 20, text: "facade", translation: "translation" },
  { id: 21, text: "facade", translation: "translation" },
  { id: 22, text: "facade", translation: "translation" },
  { id: 23, text: "facade", translation: "translation" },
  { id: 24, text: "facade", translation: "translation" },
  { id: 25, text: "facade", translation: "translation" },
  { id: 26, text: "facade", translation: "translation" },
  { id: 27, text: "facade", translation: "translation" },
  { id: 28, text: "facade", translation: "translation" },
  { id: 29, text: "facade", translation: "translation" },
  { id: 30, text: "facade", translation: "translation" },
];

const group2 = [
  { id: 1, text: "facade", translation: "translation" },
  { id: 2, text: "facade", translation: "translation" },
  { id: 3, text: "facade", translation: "translation" },
  { id: 4, text: "facade", translation: "translation" },
  { id: 5, text: "facade", translation: "translation" },
  { id: 6, text: "facade", translation: "translation" },
  { id: 7, text: "facade", translation: "translation" },
  { id: 8, text: "facade", translation: "translation" },
  { id: 9, text: "facade", translation: "translation" },
  { id: 10, text: "facade", translation: "translation" },
  { id: 11, text: "facade", translation: "translation" },
  { id: 12, text: "facade", translation: "translation" },
  { id: 13, text: "facade", translation: "translation" },
  { id: 14, text: "facade", translation: "translation" },
  { id: 15, text: "facade", translation: "translation" },
  { id: 16, text: "facade", translation: "translation" },
  { id: 17, text: "facade", translation: "translation" },
  { id: 18, text: "facade", translation: "translation" },
  { id: 19, text: "facade", translation: "translation" },
  { id: 20, text: "facade", translation: "translation" },
  { id: 21, text: "facade", translation: "translation" },
  { id: 22, text: "facade", translation: "translation" },
  { id: 23, text: "facade", translation: "translation" },
  { id: 24, text: "facade", translation: "translation" },
  { id: 25, text: "facade", translation: "translation" },
];

const group3 = [
  { id: 1, text: "facade", translation: "translation" },
  { id: 2, text: "facade", translation: "translation" },
  { id: 3, text: "facade", translation: "translation" },
  { id: 4, text: "facade", translation: "translation" },
  { id: 5, text: "facade", translation: "translation" },
  { id: 6, text: "facade", translation: "translation" },
  { id: 7, text: "facade", translation: "translation" },
  { id: 8, text: "facade", translation: "translation" },
  { id: 9, text: "facade", translation: "translation" },
  { id: 10, text: "facade", translation: "translation" },
  { id: 11, text: "facade", translation: "translation" },
  { id: 12, text: "facade", translation: "translation" },
  { id: 13, text: "facade", translation: "translation" },
  { id: 14, text: "facade", translation: "translation" },
  { id: 15, text: "facade", translation: "translation" },
  { id: 16, text: "facade", translation: "translation" },
  { id: 17, text: "facade", translation: "translation" },
  { id: 18, text: "facade", translation: "translation" },
  { id: 19, text: "facade", translation: "translation" },
  { id: 20, text: "facade", translation: "translation" },
  { id: 21, text: "facade", translation: "translation" },
  { id: 22, text: "facade", translation: "translation" },
  { id: 23, text: "facade", translation: "translation" },
  { id: 24, text: "facade", translation: "translation" },
  { id: 25, text: "facade", translation: "translation" },
];

const group4 = [
  { id: 1, text: "facade", translation: "translation" },
  { id: 2, text: "facade", translation: "translation" },
  { id: 3, text: "facade", translation: "translation" },
  { id: 4, text: "facade", translation: "translation" },
  { id: 5, text: "facade", translation: "translation" },
  { id: 6, text: "facade", translation: "translation" },
  { id: 7, text: "facade", translation: "translation" },
  { id: 8, text: "facade", translation: "translation" },
  { id: 9, text: "facade", translation: "translation" },
  { id: 10, text: "facade", translation: "translation" },
  { id: 11, text: "facade", translation: "translation" },
  { id: 12, text: "facade", translation: "translation" },
  { id: 13, text: "facade", translation: "translation" },
  { id: 14, text: "facade", translation: "translation" },
  { id: 15, text: "facade", translation: "translation" },
  { id: 16, text: "facade", translation: "translation" },
  { id: 17, text: "facade", translation: "translation" },
  { id: 18, text: "facade", translation: "translation" },
  { id: 19, text: "facade", translation: "translation" },
  { id: 20, text: "facade", translation: "translation" },
];

module.exports = { group1, group2, group3, group4 };
